datacenter: us-east-1
developerMode: true
scyllaArgs: "--smp 1 --memory 256M"
racks:
  - members: 1
    name: us-east-1-a
    placement:
      nodeAffinity: {}
      podAffinity: {}
      podAntiAffinity: {}
      tolerations: []
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: "2"
        memory: 4Gi
    scyllaConfig: scylla-config-f2b364
    storage:
      capacity: 16Gi
      storageClassName: standard
