---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: namespaces
build:
  artifacts: []
manifests:
  kustomize:
    paths:
    - develop/manifests/namespaces
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: operators
requires:
- configs:
  - namespaces
build:
  artifacts: []
manifests:
  kustomize:
    paths:
    - develop/manifests/rabbitmq-operator
deploy:
  kubectl: {}
  helm:
    releases:
    - name: cert-manager
      repo: https://charts.jetstack.io
      remoteChart: cert-manager
      namespace: cert-manager
      createNamespace: true
      version: v1.19.3
      valuesFiles:
      - develop/manifests/cert-manager/values.yaml
    - name: scylladb-operator
      repo: https://scylla-operator-charts.storage.googleapis.com/stable
      remoteChart: scylla-operator
      namespace: scylla-operator
      createNamespace: true
      wait: true
      version: v1.19.1
      valuesFiles:
      - develop/manifests/scylla-operator/values.yaml
    - name: cloudnative-pg
      repo: https://cloudnative-pg.github.io/charts
      remoteChart: cloudnative-pg
      namespace: cloudnative-pg
      createNamespace: true
      wait: true
      version:  0.27.1
      valuesFiles:
      - develop/manifests/cloudnative-pg/values.yaml
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: dependencies
requires:
- configs:
  - namespaces
  - operators
manifests:
  kustomize:
    paths:
    - develop/manifests/authelia
    - develop/manifests/postgres
    - develop/manifests/rabbitmq
deploy:
  kubectl: {}
  helm:
    releases:
    - name: seaweedfs
      repo: https://seaweedfs.github.io/seaweedfs/helm
      remoteChart: seaweedfs
      namespace: seaweedfs
      createNamespace: true
      version: 4.0.410
      valuesFiles:
      - develop/manifests/seaweedfs/values.yaml
    - name: scylladb
      repo: https://scylla-operator-charts.storage.googleapis.com/stable
      remoteChart: scylla
      namespace: scylladb
      createNamespace: true
      version: v1.19.1
      valuesFiles:
      - develop/manifests/scylladb/values.yaml
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: apps
requires:
- configs:
  - namespaces
  - dependencies
build:
  local:
    useBuildkit: true
  artifacts:
  - image: ghcr.io/walnuts1018/beast/apiserver
    context: .
    docker:
      dockerfile: Dockerfile.apiserver
  - image: ghcr.io/walnuts1018/beast/encoder
    context: ./encoder
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
    - develop/manifests/apiserver
    - develop/manifests/encoder
deploy:
  kubectl: {}
