// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/Code-Hex/synchro"
	"github.com/Code-Hex/synchro/tz"
	"github.com/walnuts1018/beast/apiserver/graph/scalar"
)

type CompleteUploadInput struct {
	UploadSessionID string `json:"uploadSessionId"`
}

type CreateUploadSessionInput struct {
	FileSizeBytes  int           `json:"fileSizeBytes"`
	ContentType    string        `json:"contentType"`
	ChecksumSha256 scalar.Base64 `json:"checksumSha256,omitempty"`
}

// Device Keyで暗号化されたShared Key秘密鍵の配布情報。
type DeviceWrappedSharedKey struct {
	DeviceID                  string               `json:"deviceId"`
	DevicePublicKeyPem        string               `json:"devicePublicKeyPem"`
	SharedKeyVersion          int                  `json:"sharedKeyVersion"`
	EncryptedSharedPrivateKey scalar.Base64        `json:"encryptedSharedPrivateKey"`
	CreatedAt                 synchro.Time[tz.UTC] `json:"createdAt"`
}

// 暗号化データに付与するEnvelope Encryptionメタデータ。
type EncryptionMetadata struct {
	Algorithm        EncryptionAlgorithm `json:"algorithm"`
	KeyVersion       int                 `json:"keyVersion"`
	Nonce            scalar.Base64       `json:"nonce"`
	EncryptedDataKey scalar.Base64       `json:"encryptedDataKey"`
}

type Me struct {
	UserID                  string                    `json:"userId"`
	SharedKeyVersions       []*SharedKeyVersion       `json:"sharedKeyVersions"`
	DeviceWrappedSharedKeys []*DeviceWrappedSharedKey `json:"deviceWrappedSharedKeys"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PaginationInput struct {
	After *string `json:"after,omitempty"`
	First int     `json:"first"`
}

// 再生時にクライアントが復号に必要な情報を取得するためのトークン。
// 復号処理は常にクライアントで実行される。
type PlaybackGrant struct {
	VideoID     string               `json:"videoId"`
	ManifestURL string               `json:"manifestUrl"`
	ExpiresAt   synchro.Time[tz.UTC] `json:"expiresAt"`
	Encryption  *EncryptionMetadata  `json:"encryption"`
}

// 再生履歴の1レコード。
type PlaybackHistory struct {
	ID       string               `json:"id"`
	VideoID  string               `json:"videoId"`
	PlayedAt synchro.Time[tz.UTC] `json:"playedAt"`
}

type Query struct {
}

type RateVideoInput struct {
	// 動画ID。
	VideoID string `json:"videoId"`
	// 星評価。nullを指定すると評価をクリアする。1-5の整数で星の数を指定する。
	Rating *int `json:"rating,omitempty"`
}

type RecordPlaybackInput struct {
	VideoID string `json:"videoId"`
}

type RegisterDeviceKeyInput struct {
	DeviceID                  string        `json:"deviceId"`
	DevicePublicKeyPem        string        `json:"devicePublicKeyPem"`
	EncryptedSharedPrivateKey scalar.Base64 `json:"encryptedSharedPrivateKey"`
	SharedKeyVersion          int           `json:"sharedKeyVersion"`
}

type RegisterSharedKeyInput struct {
	PublicKeyPem string `json:"publicKeyPem"`
}

type RetryEncodingInput struct {
	VideoID string `json:"videoId"`
}

type RevokeSharedKeyVersionInput struct {
	Version int `json:"version"`
}

// ユーザーのShared Key公開鍵のバージョン。
type SharedKeyVersion struct {
	Version      int                    `json:"version"`
	PublicKeyPem string                 `json:"publicKeyPem"`
	Status       SharedKeyVersionStatus `json:"status"`
	CreatedAt    synchro.Time[tz.UTC]   `json:"createdAt"`
	RevokedAt    *synchro.Time[tz.UTC]  `json:"revokedAt,omitempty"`
}

type Subscription struct {
}

type UpdateVideoTagsInput struct {
	VideoID string   `json:"videoId"`
	Tags    []string `json:"tags"`
}

type UploadSession struct {
	ID        string               `json:"id"`
	ObjectKey string               `json:"objectKey"`
	UploadURL string               `json:"uploadUrl"`
	ExpiresAt synchro.Time[tz.UTC] `json:"expiresAt"`
}

type Video struct {
	ID                string                `json:"id"`
	OwnerUserID       string                `json:"ownerUserId"`
	Status            VideoStatus           `json:"status"`
	UploadedAt        synchro.Time[tz.UTC]  `json:"uploadedAt"`
	ReadyAt           *synchro.Time[tz.UTC] `json:"readyAt,omitempty"`
	FailedReason      *string               `json:"failedReason,omitempty"`
	DurationMillis    *int                  `json:"durationMillis,omitempty"`
	Width             *int                  `json:"width,omitempty"`
	Height            *int                  `json:"height,omitempty"`
	Playback          *PlaybackGrant        `json:"playback,omitempty"`
	Tags              []string              `json:"tags"`
	ContentEncryption *EncryptionMetadata   `json:"contentEncryption,omitempty"`
	// 星評価。nullは未評価、1-5は星の数。
	Rating *int `json:"rating,omitempty"`
	// 再生回数。
	PlayCount int `json:"playCount"`
	// 最終再生日時。
	LastPlayedAt *synchro.Time[tz.UTC] `json:"lastPlayedAt,omitempty"`
}

type VideoConnection struct {
	Edges    []*VideoEdge `json:"edges"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type VideoEdge struct {
	Cursor string `json:"cursor"`
	Node   *Video `json:"node"`
}

type VideoEncodingProgress struct {
	VideoID   string               `json:"videoId"`
	Status    VideoStatus          `json:"status"`
	Percent   float64              `json:"percent"`
	UpdatedAt synchro.Time[tz.UTC] `json:"updatedAt"`
	Message   *string              `json:"message,omitempty"`
}

type EncryptionAlgorithm string

const (
	EncryptionAlgorithmXchacha20Poly1305 EncryptionAlgorithm = "XCHACHA20_POLY1305"
)

var AllEncryptionAlgorithm = []EncryptionAlgorithm{
	EncryptionAlgorithmXchacha20Poly1305,
}

func (e EncryptionAlgorithm) IsValid() bool {
	switch e {
	case EncryptionAlgorithmXchacha20Poly1305:
		return true
	}
	return false
}

func (e EncryptionAlgorithm) String() string {
	return string(e)
}

func (e *EncryptionAlgorithm) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EncryptionAlgorithm(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EncryptionAlgorithm", str)
	}
	return nil
}

func (e EncryptionAlgorithm) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EncryptionAlgorithm) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EncryptionAlgorithm) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SharedKeyVersionStatus string

const (
	SharedKeyVersionStatusActive  SharedKeyVersionStatus = "ACTIVE"
	SharedKeyVersionStatusRevoked SharedKeyVersionStatus = "REVOKED"
)

var AllSharedKeyVersionStatus = []SharedKeyVersionStatus{
	SharedKeyVersionStatusActive,
	SharedKeyVersionStatusRevoked,
}

func (e SharedKeyVersionStatus) IsValid() bool {
	switch e {
	case SharedKeyVersionStatusActive, SharedKeyVersionStatusRevoked:
		return true
	}
	return false
}

func (e SharedKeyVersionStatus) String() string {
	return string(e)
}

func (e *SharedKeyVersionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SharedKeyVersionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SharedKeyVersionStatus", str)
	}
	return nil
}

func (e SharedKeyVersionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SharedKeyVersionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SharedKeyVersionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VideoStatus string

const (
	VideoStatusUploaded VideoStatus = "UPLOADED"
	VideoStatusEncoding VideoStatus = "ENCODING"
	VideoStatusReady    VideoStatus = "READY"
	VideoStatusFailed   VideoStatus = "FAILED"
)

var AllVideoStatus = []VideoStatus{
	VideoStatusUploaded,
	VideoStatusEncoding,
	VideoStatusReady,
	VideoStatusFailed,
}

func (e VideoStatus) IsValid() bool {
	switch e {
	case VideoStatusUploaded, VideoStatusEncoding, VideoStatusReady, VideoStatusFailed:
		return true
	}
	return false
}

func (e VideoStatus) String() string {
	return string(e)
}

func (e *VideoStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VideoStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VideoStatus", str)
	}
	return nil
}

func (e VideoStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VideoStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VideoStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
