apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beast-apiserver
  name: beast-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beast-apiserver
  template:
    metadata:
      labels:
        app: beast-apiserver
    spec:
      containers:
      - name: apiserver
        image: ghcr.io/walnuts1018/beast/apiserver:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: RUST_BACKTRACE
          value: "1"
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      securityContext:
        runAsGroup: 65532
        runAsUser: 65532
      volumes:
      - emptyDir: {}
        name: tmp
