// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_keys.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDeviceWrappedSharedKeys = `-- name: ListDeviceWrappedSharedKeys :many
SELECT
    device_id,
    device_public_key_pem,
    shared_key_version,
    encrypted_shared_private_key,
    created_at
FROM
    device_wrapped_shared_keys
WHERE
    user_id = $1
ORDER BY
    created_at DESC
`

type ListDeviceWrappedSharedKeysRow struct {
	DeviceID                  string
	DevicePublicKeyPem        string
	SharedKeyVersion          int32
	EncryptedSharedPrivateKey []byte
	CreatedAt                 pgtype.Timestamptz
}

func (q *Queries) ListDeviceWrappedSharedKeys(ctx context.Context, userID string) ([]ListDeviceWrappedSharedKeysRow, error) {
	rows, err := q.db.Query(ctx, listDeviceWrappedSharedKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceWrappedSharedKeysRow{}
	for rows.Next() {
		var i ListDeviceWrappedSharedKeysRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.DevicePublicKeyPem,
			&i.SharedKeyVersion,
			&i.EncryptedSharedPrivateKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceWrappedSharedKey = `-- name: UpsertDeviceWrappedSharedKey :exec
INSERT INTO
    device_wrapped_shared_keys (
        user_id,
        device_id,
        device_public_key_pem,
        shared_key_version,
        encrypted_shared_private_key,
        created_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    ) ON CONFLICT (user_id, device_id) DO
UPDATE
SET
    device_public_key_pem = EXCLUDED.device_public_key_pem,
    shared_key_version = EXCLUDED.shared_key_version,
    encrypted_shared_private_key = EXCLUDED.encrypted_shared_private_key,
    created_at = EXCLUDED.created_at
`

type UpsertDeviceWrappedSharedKeyParams struct {
	UserID                    string
	DeviceID                  string
	DevicePublicKeyPem        string
	SharedKeyVersion          int32
	EncryptedSharedPrivateKey []byte
	CreatedAt                 pgtype.Timestamptz
}

func (q *Queries) UpsertDeviceWrappedSharedKey(ctx context.Context, arg UpsertDeviceWrappedSharedKeyParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceWrappedSharedKey,
		arg.UserID,
		arg.DeviceID,
		arg.DevicePublicKeyPem,
		arg.SharedKeyVersion,
		arg.EncryptedSharedPrivateKey,
		arg.CreatedAt,
	)
	return err
}
