// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: encoding_progress.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEncodingProgress = `-- name: GetEncodingProgress :one
SELECT
    video_id,
    owner_user,
    status,
    percent,
    updated_at,
    message
FROM
    encoding_progress
WHERE
    video_id = $1
`

func (q *Queries) GetEncodingProgress(ctx context.Context, videoID string) (EncodingProgress, error) {
	row := q.db.QueryRow(ctx, getEncodingProgress, videoID)
	var i EncodingProgress
	err := row.Scan(
		&i.VideoID,
		&i.OwnerUser,
		&i.Status,
		&i.Percent,
		&i.UpdatedAt,
		&i.Message,
	)
	return i, err
}

const upsertEncodingProgress = `-- name: UpsertEncodingProgress :exec
INSERT INTO
    encoding_progress (
        video_id,
        owner_user,
        status,
        percent,
        updated_at,
        message
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    ) ON CONFLICT (video_id) DO
UPDATE
SET
    owner_user = EXCLUDED.owner_user,
    status = EXCLUDED.status,
    percent = EXCLUDED.percent,
    updated_at = EXCLUDED.updated_at,
    message = EXCLUDED.message
`

type UpsertEncodingProgressParams struct {
	VideoID   string
	OwnerUser string
	Status    string
	Percent   float64
	UpdatedAt pgtype.Timestamptz
	Message   pgtype.Text
}

func (q *Queries) UpsertEncodingProgress(ctx context.Context, arg UpsertEncodingProgressParams) error {
	_, err := q.db.Exec(ctx, upsertEncodingProgress,
		arg.VideoID,
		arg.OwnerUser,
		arg.Status,
		arg.Percent,
		arg.UpdatedAt,
		arg.Message,
	)
	return err
}
