// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeviceWrappedSharedKey struct {
	UserID                    string
	DeviceID                  string
	DevicePublicKeyPem        string
	SharedKeyVersion          int32
	EncryptedSharedPrivateKey []byte
	CreatedAt                 pgtype.Timestamptz
}

type EncodingProgress struct {
	VideoID   string
	OwnerUser string
	Status    string
	Percent   float64
	UpdatedAt pgtype.Timestamptz
	Message   pgtype.Text
}

type PlaybackHistory struct {
	ID          string
	VideoID     string
	OwnerUserID string
	PlayedAt    pgtype.Timestamptz
}

type SharedKeyVersion struct {
	UserID       string
	Version      int32
	PublicKeyPem string
	Status       string
	CreatedAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
}

type UploadSession struct {
	ID        string
	OwnerUser string
	ObjectKey string
	UploadUrl string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Video struct {
	ID                          string
	OwnerUserID                 string
	Status                      string
	SourceObjectKey             string
	EncodedObjectKey            pgtype.Text
	UploadedAt                  pgtype.Timestamptz
	ReadyAt                     pgtype.Timestamptz
	FailedReason                pgtype.Text
	DurationMillis              *int32
	Width                       *int32
	Height                      *int32
	PlaybackManifestUrl         pgtype.Text
	PlaybackExpiresAt           pgtype.Timestamptz
	PlaybackEncAlgorithm        pgtype.Text
	PlaybackEncKeyVersion       *int32
	PlaybackEncNonce            []byte
	PlaybackEncEncryptedDataKey []byte
	ContentEncAlgorithm         pgtype.Text
	ContentEncKeyVersion        *int32
	ContentEncNonce             []byte
	ContentEncEncryptedDataKey  []byte
	Rating                      *int32
	PlayCount                   int32
	LastPlayedAt                pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
}

type VideoTag struct {
	VideoID   string
	Tag       string
	CreatedAt pgtype.Timestamptz
}
