// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playback_histories.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPlaybackHistory = `-- name: InsertPlaybackHistory :exec
INSERT INTO
    playback_histories (id, video_id, owner_user_id, played_at)
VALUES
    ($1, $2, $3, $4)
`

type InsertPlaybackHistoryParams struct {
	ID          string
	VideoID     string
	OwnerUserID string
	PlayedAt    pgtype.Timestamptz
}

func (q *Queries) InsertPlaybackHistory(ctx context.Context, arg InsertPlaybackHistoryParams) error {
	_, err := q.db.Exec(ctx, insertPlaybackHistory,
		arg.ID,
		arg.VideoID,
		arg.OwnerUserID,
		arg.PlayedAt,
	)
	return err
}

const listPlaybackHistoriesByVideo = `-- name: ListPlaybackHistoriesByVideo :many
SELECT
    id,
    video_id,
    owner_user_id,
    played_at
FROM
    playback_histories
WHERE
    video_id = $1
ORDER BY
    played_at DESC
LIMIT
    $2
`

type ListPlaybackHistoriesByVideoParams struct {
	VideoID    string
	LimitCount int32
}

func (q *Queries) ListPlaybackHistoriesByVideo(ctx context.Context, arg ListPlaybackHistoriesByVideoParams) ([]PlaybackHistory, error) {
	rows, err := q.db.Query(ctx, listPlaybackHistoriesByVideo, arg.VideoID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlaybackHistory{}
	for rows.Next() {
		var i PlaybackHistory
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.OwnerUserID,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
