// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) error
	CreateVideo(ctx context.Context, arg CreateVideoParams) error
	DeleteUploadSession(ctx context.Context, id string) error
	GetEncodingProgress(ctx context.Context, videoID string) (EncodingProgress, error)
	GetNextSharedKeyVersion(ctx context.Context, userID string) (int32, error)
	GetSharedKeyVersion(ctx context.Context, arg GetSharedKeyVersionParams) (GetSharedKeyVersionRow, error)
	GetUploadSessionByID(ctx context.Context, id string) (UploadSession, error)
	GetVideoByID(ctx context.Context, id string) (Video, error)
	InsertSharedKeyVersion(ctx context.Context, arg InsertSharedKeyVersionParams) error
	ListDeviceWrappedSharedKeys(ctx context.Context, userID string) ([]ListDeviceWrappedSharedKeysRow, error)
	ListSharedKeyVersions(ctx context.Context, userID string) ([]ListSharedKeyVersionsRow, error)
	ListVideosByOwner(ctx context.Context, arg ListVideosByOwnerParams) ([]Video, error)
	LoadVideoUploadedAt(ctx context.Context, arg LoadVideoUploadedAtParams) (pgtype.Timestamptz, error)
	RevokeSharedKeyVersion(ctx context.Context, arg RevokeSharedKeyVersionParams) (RevokeSharedKeyVersionRow, error)
	UpdateVideo(ctx context.Context, arg UpdateVideoParams) (int64, error)
	UpsertDeviceWrappedSharedKey(ctx context.Context, arg UpsertDeviceWrappedSharedKeyParams) error
	UpsertEncodingProgress(ctx context.Context, arg UpsertEncodingProgressParams) error
}

var _ Querier = (*Queries)(nil)
