// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shared_keys.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNextSharedKeyVersion = `-- name: GetNextSharedKeyVersion :one
SELECT
    COALESCE(MAX(version), 0) + 1 AS next_version
FROM
    shared_key_versions
WHERE
    user_id = $1
`

func (q *Queries) GetNextSharedKeyVersion(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, getNextSharedKeyVersion, userID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const getSharedKeyVersion = `-- name: GetSharedKeyVersion :one
SELECT
    version,
    public_key_pem,
    status,
    created_at,
    revoked_at
FROM
    shared_key_versions
WHERE
    user_id = $1
    AND version = $2
`

type GetSharedKeyVersionParams struct {
	UserID  string
	Version int32
}

type GetSharedKeyVersionRow struct {
	Version      int32
	PublicKeyPem string
	Status       string
	CreatedAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
}

func (q *Queries) GetSharedKeyVersion(ctx context.Context, arg GetSharedKeyVersionParams) (GetSharedKeyVersionRow, error) {
	row := q.db.QueryRow(ctx, getSharedKeyVersion, arg.UserID, arg.Version)
	var i GetSharedKeyVersionRow
	err := row.Scan(
		&i.Version,
		&i.PublicKeyPem,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertSharedKeyVersion = `-- name: InsertSharedKeyVersion :exec
INSERT INTO
    shared_key_versions (
        user_id,
        version,
        public_key_pem,
        status,
        created_at,
        revoked_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
`

type InsertSharedKeyVersionParams struct {
	UserID       string
	Version      int32
	PublicKeyPem string
	Status       string
	CreatedAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
}

func (q *Queries) InsertSharedKeyVersion(ctx context.Context, arg InsertSharedKeyVersionParams) error {
	_, err := q.db.Exec(ctx, insertSharedKeyVersion,
		arg.UserID,
		arg.Version,
		arg.PublicKeyPem,
		arg.Status,
		arg.CreatedAt,
		arg.RevokedAt,
	)
	return err
}

const listSharedKeyVersions = `-- name: ListSharedKeyVersions :many
SELECT
    version,
    public_key_pem,
    status,
    created_at,
    revoked_at
FROM
    shared_key_versions
WHERE
    user_id = $1
ORDER BY
    version DESC
`

type ListSharedKeyVersionsRow struct {
	Version      int32
	PublicKeyPem string
	Status       string
	CreatedAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
}

func (q *Queries) ListSharedKeyVersions(ctx context.Context, userID string) ([]ListSharedKeyVersionsRow, error) {
	rows, err := q.db.Query(ctx, listSharedKeyVersions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedKeyVersionsRow{}
	for rows.Next() {
		var i ListSharedKeyVersionsRow
		if err := rows.Scan(
			&i.Version,
			&i.PublicKeyPem,
			&i.Status,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSharedKeyVersion = `-- name: RevokeSharedKeyVersion :one
UPDATE
    shared_key_versions
SET
    status = $1,
    revoked_at = $2
WHERE
    user_id = $3
    AND version = $4 RETURNING version,
    public_key_pem,
    status,
    created_at,
    revoked_at
`

type RevokeSharedKeyVersionParams struct {
	Status    string
	RevokedAt pgtype.Timestamptz
	UserID    string
	Version   int32
}

type RevokeSharedKeyVersionRow struct {
	Version      int32
	PublicKeyPem string
	Status       string
	CreatedAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
}

func (q *Queries) RevokeSharedKeyVersion(ctx context.Context, arg RevokeSharedKeyVersionParams) (RevokeSharedKeyVersionRow, error) {
	row := q.db.QueryRow(ctx, revokeSharedKeyVersion,
		arg.Status,
		arg.RevokedAt,
		arg.UserID,
		arg.Version,
	)
	var i RevokeSharedKeyVersionRow
	err := row.Scan(
		&i.Version,
		&i.PublicKeyPem,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
