// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_sessions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUploadSession = `-- name: CreateUploadSession :exec
INSERT INTO
    upload_sessions (
        id,
        owner_user,
        object_key,
        upload_url,
        expires_at,
        created_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
`

type CreateUploadSessionParams struct {
	ID        string
	OwnerUser string
	ObjectKey string
	UploadUrl string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) error {
	_, err := q.db.Exec(ctx, createUploadSession,
		arg.ID,
		arg.OwnerUser,
		arg.ObjectKey,
		arg.UploadUrl,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteUploadSession = `-- name: DeleteUploadSession :exec
DELETE FROM
    upload_sessions
WHERE
    id = $1
`

func (q *Queries) DeleteUploadSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUploadSession, id)
	return err
}

const getUploadSessionByID = `-- name: GetUploadSessionByID :one
SELECT
    id,
    owner_user,
    object_key,
    upload_url,
    expires_at,
    created_at
FROM
    upload_sessions
WHERE
    id = $1
`

func (q *Queries) GetUploadSessionByID(ctx context.Context, id string) (UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSessionByID, id)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerUser,
		&i.ObjectKey,
		&i.UploadUrl,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
