// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :exec
INSERT INTO
    videos (
        id,
        owner_user_id,
        status,
        uploaded_at,
        ready_at,
        failed_reason,
        duration_millis,
        width,
        height,
        playback_manifest_url,
        playback_expires_at,
        playback_enc_algorithm,
        playback_enc_key_version,
        playback_enc_nonce,
        playback_enc_encrypted_data_key,
        encrypted_tags,
        tag_enc_algorithm,
        tag_enc_key_version,
        tag_enc_nonce,
        tag_enc_encrypted_data_key,
        content_enc_algorithm,
        content_enc_key_version,
        content_enc_nonce,
        content_enc_encrypted_data_key,
        created_at,
        updated_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26
    )
`

type CreateVideoParams struct {
	ID                          string
	OwnerUserID                 string
	Status                      string
	UploadedAt                  pgtype.Timestamptz
	ReadyAt                     pgtype.Timestamptz
	FailedReason                pgtype.Text
	DurationMillis              *int32
	Width                       *int32
	Height                      *int32
	PlaybackManifestUrl         pgtype.Text
	PlaybackExpiresAt           pgtype.Timestamptz
	PlaybackEncAlgorithm        pgtype.Text
	PlaybackEncKeyVersion       *int32
	PlaybackEncNonce            []byte
	PlaybackEncEncryptedDataKey []byte
	EncryptedTags               []byte
	TagEncAlgorithm             string
	TagEncKeyVersion            int32
	TagEncNonce                 []byte
	TagEncEncryptedDataKey      []byte
	ContentEncAlgorithm         pgtype.Text
	ContentEncKeyVersion        *int32
	ContentEncNonce             []byte
	ContentEncEncryptedDataKey  []byte
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) error {
	_, err := q.db.Exec(ctx, createVideo,
		arg.ID,
		arg.OwnerUserID,
		arg.Status,
		arg.UploadedAt,
		arg.ReadyAt,
		arg.FailedReason,
		arg.DurationMillis,
		arg.Width,
		arg.Height,
		arg.PlaybackManifestUrl,
		arg.PlaybackExpiresAt,
		arg.PlaybackEncAlgorithm,
		arg.PlaybackEncKeyVersion,
		arg.PlaybackEncNonce,
		arg.PlaybackEncEncryptedDataKey,
		arg.EncryptedTags,
		arg.TagEncAlgorithm,
		arg.TagEncKeyVersion,
		arg.TagEncNonce,
		arg.TagEncEncryptedDataKey,
		arg.ContentEncAlgorithm,
		arg.ContentEncKeyVersion,
		arg.ContentEncNonce,
		arg.ContentEncEncryptedDataKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT
    id,
    owner_user_id,
    status,
    uploaded_at,
    ready_at,
    failed_reason,
    duration_millis,
    width,
    height,
    playback_manifest_url,
    playback_expires_at,
    playback_enc_algorithm,
    playback_enc_key_version,
    playback_enc_nonce,
    playback_enc_encrypted_data_key,
    encrypted_tags,
    tag_enc_algorithm,
    tag_enc_key_version,
    tag_enc_nonce,
    tag_enc_encrypted_data_key,
    content_enc_algorithm,
    content_enc_key_version,
    content_enc_nonce,
    content_enc_encrypted_data_key,
    created_at,
    updated_at
FROM
    videos
WHERE
    id = $1
`

func (q *Queries) GetVideoByID(ctx context.Context, id string) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Status,
		&i.UploadedAt,
		&i.ReadyAt,
		&i.FailedReason,
		&i.DurationMillis,
		&i.Width,
		&i.Height,
		&i.PlaybackManifestUrl,
		&i.PlaybackExpiresAt,
		&i.PlaybackEncAlgorithm,
		&i.PlaybackEncKeyVersion,
		&i.PlaybackEncNonce,
		&i.PlaybackEncEncryptedDataKey,
		&i.EncryptedTags,
		&i.TagEncAlgorithm,
		&i.TagEncKeyVersion,
		&i.TagEncNonce,
		&i.TagEncEncryptedDataKey,
		&i.ContentEncAlgorithm,
		&i.ContentEncKeyVersion,
		&i.ContentEncNonce,
		&i.ContentEncEncryptedDataKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVideosByOwner = `-- name: ListVideosByOwner :many
SELECT
    id,
    owner_user_id,
    status,
    uploaded_at,
    ready_at,
    failed_reason,
    duration_millis,
    width,
    height,
    playback_manifest_url,
    playback_expires_at,
    playback_enc_algorithm,
    playback_enc_key_version,
    playback_enc_nonce,
    playback_enc_encrypted_data_key,
    encrypted_tags,
    tag_enc_algorithm,
    tag_enc_key_version,
    tag_enc_nonce,
    tag_enc_encrypted_data_key,
    content_enc_algorithm,
    content_enc_key_version,
    content_enc_nonce,
    content_enc_encrypted_data_key,
    created_at,
    updated_at
FROM
    videos
WHERE
    owner_user_id = $1
    AND (
        $2 :: text IS NULL
        OR status = $2
    )
    AND (
        $3 :: timestamptz IS NULL
        OR (uploaded_at, id) < (
            $3,
            $4::text
        )
    )
ORDER BY
    uploaded_at DESC,
    id DESC
LIMIT
    $5
`

type ListVideosByOwnerParams struct {
	OwnerUserID      string
	Status           pgtype.Text
	CursorUploadedAt pgtype.Timestamptz
	CursorID         pgtype.Text
	LimitCount       int32
}

func (q *Queries) ListVideosByOwner(ctx context.Context, arg ListVideosByOwnerParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosByOwner,
		arg.OwnerUserID,
		arg.Status,
		arg.CursorUploadedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Status,
			&i.UploadedAt,
			&i.ReadyAt,
			&i.FailedReason,
			&i.DurationMillis,
			&i.Width,
			&i.Height,
			&i.PlaybackManifestUrl,
			&i.PlaybackExpiresAt,
			&i.PlaybackEncAlgorithm,
			&i.PlaybackEncKeyVersion,
			&i.PlaybackEncNonce,
			&i.PlaybackEncEncryptedDataKey,
			&i.EncryptedTags,
			&i.TagEncAlgorithm,
			&i.TagEncKeyVersion,
			&i.TagEncNonce,
			&i.TagEncEncryptedDataKey,
			&i.ContentEncAlgorithm,
			&i.ContentEncKeyVersion,
			&i.ContentEncNonce,
			&i.ContentEncEncryptedDataKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadVideoUploadedAt = `-- name: LoadVideoUploadedAt :one
SELECT
    uploaded_at
FROM
    videos
WHERE
    id = $1
    AND owner_user_id = $2
`

type LoadVideoUploadedAtParams struct {
	ID          string
	OwnerUserID string
}

func (q *Queries) LoadVideoUploadedAt(ctx context.Context, arg LoadVideoUploadedAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, loadVideoUploadedAt, arg.ID, arg.OwnerUserID)
	var uploaded_at pgtype.Timestamptz
	err := row.Scan(&uploaded_at)
	return uploaded_at, err
}

const updateVideo = `-- name: UpdateVideo :execrows
UPDATE
    videos
SET
    owner_user_id = $1,
    status = $2,
    uploaded_at = $3,
    ready_at = $4,
    failed_reason = $5,
    duration_millis = $6,
    width = $7,
    height = $8,
    playback_manifest_url = $9,
    playback_expires_at = $10,
    playback_enc_algorithm = $11,
    playback_enc_key_version = $12,
    playback_enc_nonce = $13,
    playback_enc_encrypted_data_key = $14,
    encrypted_tags = $15,
    tag_enc_algorithm = $16,
    tag_enc_key_version = $17,
    tag_enc_nonce = $18,
    tag_enc_encrypted_data_key = $19,
    content_enc_algorithm = $20,
    content_enc_key_version = $21,
    content_enc_nonce = $22,
    content_enc_encrypted_data_key = $23,
    created_at = $24,
    updated_at = $25
WHERE
    id = $26
`

type UpdateVideoParams struct {
	OwnerUserID                 string
	Status                      string
	UploadedAt                  pgtype.Timestamptz
	ReadyAt                     pgtype.Timestamptz
	FailedReason                pgtype.Text
	DurationMillis              *int32
	Width                       *int32
	Height                      *int32
	PlaybackManifestUrl         pgtype.Text
	PlaybackExpiresAt           pgtype.Timestamptz
	PlaybackEncAlgorithm        pgtype.Text
	PlaybackEncKeyVersion       *int32
	PlaybackEncNonce            []byte
	PlaybackEncEncryptedDataKey []byte
	EncryptedTags               []byte
	TagEncAlgorithm             string
	TagEncKeyVersion            int32
	TagEncNonce                 []byte
	TagEncEncryptedDataKey      []byte
	ContentEncAlgorithm         pgtype.Text
	ContentEncKeyVersion        *int32
	ContentEncNonce             []byte
	ContentEncEncryptedDataKey  []byte
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	ID                          string
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVideo,
		arg.OwnerUserID,
		arg.Status,
		arg.UploadedAt,
		arg.ReadyAt,
		arg.FailedReason,
		arg.DurationMillis,
		arg.Width,
		arg.Height,
		arg.PlaybackManifestUrl,
		arg.PlaybackExpiresAt,
		arg.PlaybackEncAlgorithm,
		arg.PlaybackEncKeyVersion,
		arg.PlaybackEncNonce,
		arg.PlaybackEncEncryptedDataKey,
		arg.EncryptedTags,
		arg.TagEncAlgorithm,
		arg.TagEncKeyVersion,
		arg.TagEncNonce,
		arg.TagEncEncryptedDataKey,
		arg.ContentEncAlgorithm,
		arg.ContentEncKeyVersion,
		arg.ContentEncNonce,
		arg.ContentEncEncryptedDataKey,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
