// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_tags.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteVideoTags = `-- name: DeleteVideoTags :exec
DELETE FROM
    video_tags
WHERE
    video_id = $1
`

func (q *Queries) DeleteVideoTags(ctx context.Context, videoID string) error {
	_, err := q.db.Exec(ctx, deleteVideoTags, videoID)
	return err
}

const getVideoTags = `-- name: GetVideoTags :many
SELECT
    tag
FROM
    video_tags
WHERE
    video_id = $1
ORDER BY
    tag
`

func (q *Queries) GetVideoTags(ctx context.Context, videoID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getVideoTags, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoTagsBatch = `-- name: GetVideoTagsBatch :many
SELECT
    video_id,
    tag
FROM
    video_tags
WHERE
    video_id = ANY($1 :: text [])
ORDER BY
    video_id,
    tag
`

type GetVideoTagsBatchRow struct {
	VideoID string
	Tag     string
}

func (q *Queries) GetVideoTagsBatch(ctx context.Context, videoIds []string) ([]GetVideoTagsBatchRow, error) {
	rows, err := q.db.Query(ctx, getVideoTagsBatch, videoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVideoTagsBatchRow{}
	for rows.Next() {
		var i GetVideoTagsBatchRow
		if err := rows.Scan(&i.VideoID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVideoTag = `-- name: InsertVideoTag :exec
INSERT INTO
    video_tags (video_id, tag, created_at)
VALUES
    ($1, $2, $3)
`

type InsertVideoTagParams struct {
	VideoID   string
	Tag       string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertVideoTag(ctx context.Context, arg InsertVideoTagParams) error {
	_, err := q.db.Exec(ctx, insertVideoTag, arg.VideoID, arg.Tag, arg.CreatedAt)
	return err
}
