apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  labels:
    app: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
      - name: authelia
        image: authelia/authelia:4.38.19
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9091
          name: http
        readinessProbe:
          tcpSocket:
            port: 9091
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 6
        livenessProbe:
          tcpSocket:
            port: 9091
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 512Mi
        volumeMounts:
        - name: authelia-config
          mountPath: /config
          readOnly: true
        - name: authelia-data
          mountPath: /data
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
      volumes:
      - name: authelia-config
        secret:
          secretName: authelia-config
      - name: authelia-data
        emptyDir: {}
