apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
- deployment.yaml
- service.yaml
configMapGenerator:
- name: authelia-config
  files:
  - configuration.yml=./config/configuration.yml
  - users_database.yaml=./config/users_database.yaml
