// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type CreateVideoInput struct {
	EncryptedTags string           `json:"encryptedTags"`
	SharedKeyID   string           `json:"sharedKeyID"`
	Encryption    *EncryptionInput `json:"encryption"`
}

type DeviceKey struct {
	ID                        string `json:"id"`
	DeviceID                  string `json:"deviceID"`
	SharedKeyID               string `json:"sharedKeyID"`
	EncryptedSharedPrivateKey string `json:"encryptedSharedPrivateKey"`
}

type EncryptionInput struct {
	Algorithm        string `json:"algorithm"`
	ChunkSize        int    `json:"chunkSize"`
	KeyVersion       string `json:"keyVersion"`
	Nonce            string `json:"nonce"`
	EncryptedDataKey string `json:"encryptedDataKey"`
	SharedKeyID      string `json:"sharedKeyID"`
}

type EncryptionMetadata struct {
	Algorithm        string `json:"algorithm"`
	ChunkSize        int    `json:"chunkSize"`
	KeyVersion       string `json:"keyVersion"`
	Nonce            string `json:"nonce"`
	EncryptedDataKey string `json:"encryptedDataKey"`
	SharedKeyID      string `json:"sharedKeyID"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterDeviceKeyInput struct {
	DeviceID                  string `json:"deviceID"`
	SharedKeyID               string `json:"sharedKeyID"`
	EncryptedSharedPrivateKey string `json:"encryptedSharedPrivateKey"`
}

type RegisterSharedKeyInput struct {
	Version   string `json:"version"`
	PublicKey string `json:"publicKey"`
}

type SharedKey struct {
	ID        string `json:"id"`
	Version   string `json:"version"`
	PublicKey string `json:"publicKey"`
	Status    string `json:"status"`
}

type Video struct {
	ID            string              `json:"id"`
	Status        VideoStatus         `json:"status"`
	EncryptedTags string              `json:"encryptedTags"`
	PlayCount     int                 `json:"playCount"`
	Rating        *int                `json:"rating,omitempty"`
	LastPlayedAt  *time.Time          `json:"lastPlayedAt,omitempty"`
	Encryption    *EncryptionMetadata `json:"encryption"`
	VideoURL      string              `json:"videoURL"`
	Progress      float64             `json:"progress"`
}

type RecommendationKind string

const (
	RecommendationKindFavorites                 RecommendationKind = "FAVORITES"
	RecommendationKindRecentlyUnplayedFavorites RecommendationKind = "RECENTLY_UNPLAYED_FAVORITES"
	RecommendationKindUnwatched                 RecommendationKind = "UNWATCHED"
)

var AllRecommendationKind = []RecommendationKind{
	RecommendationKindFavorites,
	RecommendationKindRecentlyUnplayedFavorites,
	RecommendationKindUnwatched,
}

func (e RecommendationKind) IsValid() bool {
	switch e {
	case RecommendationKindFavorites, RecommendationKindRecentlyUnplayedFavorites, RecommendationKindUnwatched:
		return true
	}
	return false
}

func (e RecommendationKind) String() string {
	return string(e)
}

func (e *RecommendationKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RecommendationKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RecommendationKind", str)
	}
	return nil
}

func (e RecommendationKind) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RecommendationKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RecommendationKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VideoStatus string

const (
	VideoStatusUploaded VideoStatus = "UPLOADED"
	VideoStatusEncoding VideoStatus = "ENCODING"
	VideoStatusReady    VideoStatus = "READY"
	VideoStatusFailed   VideoStatus = "FAILED"
)

var AllVideoStatus = []VideoStatus{
	VideoStatusUploaded,
	VideoStatusEncoding,
	VideoStatusReady,
	VideoStatusFailed,
}

func (e VideoStatus) IsValid() bool {
	switch e {
	case VideoStatusUploaded, VideoStatusEncoding, VideoStatusReady, VideoStatusFailed:
		return true
	}
	return false
}

func (e VideoStatus) String() string {
	return string(e)
}

func (e *VideoStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VideoStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VideoStatus", str)
	}
	return nil
}

func (e VideoStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VideoStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VideoStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
