apiVersion: v1
kind: Namespace
metadata:
  name: beast
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
---
apiVersion: v1
kind: Namespace
metadata:
  name: imgproxy
---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-operator
