apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
resources:
- postgres.yaml
- databases.yaml
- imagecatalog.yaml
secretGenerator:
- behavior: create
  literals:
  - username=beast
  - password=password
  name: beast-db-password
  type: kubernetes.io/basic-auth
