package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/walnuts1018/beast/backend/graph/model"
	"github.com/walnuts1018/beast/backend/internal/domain"
)

// UpdateVideoTags is the resolver for the updateVideoTags field.
func (r *mutationResolver) UpdateVideoTags(ctx context.Context, id string, input model.UpdateVideoTagsInput) (*model.Video, error) {
	ownerID := OwnerID(ctx)
	if ownerID == "" {
		return nil, errors.New("authentication is required")
	}
	video, err := r.Store.UpdateVideoTags(ctx, ownerID, id, input.Tags)
	if err != nil {
		return nil, fmt.Errorf("update tags: %w", err)
	}
	return videoModel(video), nil
}

// RateVideo is the resolver for the rateVideo field.
func (r *mutationResolver) RateVideo(ctx context.Context, id string, rating *int) (*model.Video, error) {
	video, err := r.Store.SetRating(ctx, OwnerID(ctx), id, rating)
	if err != nil {
		return nil, err
	}
	return videoModel(video), nil
}

// RecordPlayback is the resolver for the recordPlayback field.
func (r *mutationResolver) RecordPlayback(ctx context.Context, id string) (*model.Video, error) {
	video, err := r.Store.RecordPlayback(ctx, OwnerID(ctx), id)
	if err != nil {
		return nil, err
	}
	return videoModel(video), nil
}

// Videos is the resolver for the videos field.
func (r *queryResolver) Videos(ctx context.Context) ([]*model.Video, error) {
	videos, err := r.Store.ListVideos(ctx, OwnerID(ctx))
	if err != nil {
		return nil, err
	}
	result := make([]*model.Video, 0, len(videos))
	for _, video := range videos {
		result = append(result, videoModel(video))
	}
	return result, nil
}

// Video is the resolver for the video field.
func (r *queryResolver) Video(ctx context.Context, id string) (*model.Video, error) {
	video, err := r.Store.GetVideo(ctx, OwnerID(ctx), id)
	if err != nil {
		if errors.Is(err, domain.ErrVideoNotFound) || errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	return videoModel(video), nil
}

// Recommendations is the resolver for the recommendations field.
func (r *queryResolver) Recommendations(ctx context.Context, kind model.RecommendationKind) ([]*model.Video, error) {
	videos, err := r.Store.ListVideos(ctx, OwnerID(ctx))
	if err != nil {
		return nil, err
	}
	result := make([]*model.Video, 0, len(videos))
	for _, video := range videos {
		include := false
		switch kind {
		case model.RecommendationKindFavorites:
			include = video.Rating != nil && *video.Rating >= 4
		case model.RecommendationKindRecentlyUnplayedFavorites:
			include = video.Rating != nil && *video.Rating >= 4 && (video.LastPlayedAt == nil || time.Since(*video.LastPlayedAt) > 14*24*time.Hour)
		case model.RecommendationKindUnwatched:
			include = video.PlayCount == 0
		}
		if include {
			result = append(result, videoModel(video))
		}
	}
	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
