scalar Time

enum VideoStatus {
  UPLOADED
  ENCODING
  READY
  FAILED
}

type Video {
  id: ID!
  status: VideoStatus!
  tags: [String!]!
  playCount: Int!
  rating: Int
  lastPlayedAt: Time
  videoURL: String!
  progress: Float!
}

input UpdateVideoTagsInput {
  tags: [String!]!
}

type Query {
  videos: [Video!]!
  video(id: ID!): Video
  recommendations(kind: RecommendationKind!): [Video!]!
}

enum RecommendationKind {
  FAVORITES
  RECENTLY_UNPLAYED_FAVORITES
  UNWATCHED
}

type Mutation {
  updateVideoTags(id: ID!, input: UpdateVideoTagsInput!): Video!
  rateVideo(id: ID!, rating: Int): Video!
  recordPlayback(id: ID!): Video!
}
