package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"database/sql"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/walnuts1018/beast/backend/graph/model"
	"github.com/walnuts1018/beast/backend/internal/domain"
	"github.com/walnuts1018/beast/backend/internal/store"
)

// CreateVideo is the resolver for the createVideo field.
func (r *mutationResolver) CreateVideo(ctx context.Context, input model.CreateVideoInput) (*model.Video, error) {
	ownerID := OwnerID(ctx)
	if ownerID == "" {
		return nil, errors.New("authentication is required")
	}
	if input.Encryption == nil || input.SharedKeyID != input.Encryption.SharedKeyID {
		return nil, errors.New("shared key IDs must match")
	}
	video, err := r.Store.GetVideoByObjectKey(ctx, ownerID, input.ObjectKey)
	if err != nil {
		return nil, errors.New("encrypted media object is not registered for this owner")
	}
	if video.EncryptedTags != input.EncryptedTags || video.Encryption.SharedKeyID != input.Encryption.SharedKeyID || video.Encryption.KeyVersion != input.Encryption.KeyVersion {
		return nil, errors.New("video encryption metadata does not match the registered object")
	}
	return videoModel(video), nil
}

// RateVideo is the resolver for the rateVideo field.
func (r *mutationResolver) RateVideo(ctx context.Context, id string, rating *int) (*model.Video, error) {
	video, err := r.Store.SetRating(ctx, OwnerID(ctx), id, rating)
	if err != nil {
		return nil, err
	}
	return videoModel(video), nil
}

// RecordPlayback is the resolver for the recordPlayback field.
func (r *mutationResolver) RecordPlayback(ctx context.Context, id string) (*model.Video, error) {
	video, err := r.Store.RecordPlayback(ctx, OwnerID(ctx), id)
	if err != nil {
		return nil, err
	}
	return videoModel(video), nil
}

// RegisterSharedKey is the resolver for the registerSharedKey field.
func (r *mutationResolver) RegisterSharedKey(ctx context.Context, input model.RegisterSharedKeyInput) (*model.SharedKey, error) {
	key, err := r.Store.RegisterSharedKey(ctx, store.SharedKey{ID: uuid.New().String(), OwnerID: OwnerID(ctx), Version: input.Version, PublicKey: input.PublicKey, Status: "active"})
	if err != nil {
		return nil, err
	}
	return &model.SharedKey{ID: key.ID, Version: key.Version, PublicKey: key.PublicKey, Status: key.Status}, nil
}

// RegisterDeviceKey is the resolver for the registerDeviceKey field.
func (r *mutationResolver) RegisterDeviceKey(ctx context.Context, input model.RegisterDeviceKeyInput) (*model.DeviceKey, error) {
	key, err := r.Store.RegisterDeviceKey(ctx, store.DeviceKey{ID: uuid.New().String(), OwnerID: OwnerID(ctx), DeviceID: input.DeviceID, SharedKeyID: input.SharedKeyID, EncryptedSharedPrivateKey: input.EncryptedSharedPrivateKey})
	if err != nil {
		return nil, err
	}
	return &model.DeviceKey{ID: key.ID, DeviceID: key.DeviceID, SharedKeyID: key.SharedKeyID, EncryptedSharedPrivateKey: key.EncryptedSharedPrivateKey}, nil
}

// Videos is the resolver for the videos field.
func (r *queryResolver) Videos(ctx context.Context) ([]*model.Video, error) {
	videos, err := r.Store.ListVideos(ctx, OwnerID(ctx))
	if err != nil {
		return nil, err
	}
	result := make([]*model.Video, 0, len(videos))
	for _, video := range videos {
		result = append(result, videoModel(video))
	}
	return result, nil
}

// Video is the resolver for the video field.
func (r *queryResolver) Video(ctx context.Context, id string) (*model.Video, error) {
	video, err := r.Store.GetVideo(ctx, OwnerID(ctx), id)
	if err != nil {
		if errors.Is(err, domain.ErrVideoNotFound) || errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	return videoModel(video), nil
}

// SharedKeys is the resolver for the sharedKeys field.
func (r *queryResolver) SharedKeys(ctx context.Context) ([]*model.SharedKey, error) {
	keys, err := r.Store.ListSharedKeys(ctx, OwnerID(ctx))
	if err != nil {
		return nil, err
	}
	result := make([]*model.SharedKey, 0, len(keys))
	for _, key := range keys {
		result = append(result, &model.SharedKey{ID: key.ID, Version: key.Version, PublicKey: key.PublicKey, Status: key.Status})
	}
	return result, nil
}

// DeviceKeysは、端末側でShared Key秘密鍵を復号するための暗号化鍵包みを返す。
func (r *queryResolver) DeviceKeys(ctx context.Context) ([]*model.DeviceKey, error) {
	keys, err := r.Store.ListDeviceKeys(ctx, OwnerID(ctx))
	if err != nil {
		return nil, err
	}
	result := make([]*model.DeviceKey, 0, len(keys))
	for _, key := range keys {
		result = append(result, &model.DeviceKey{ID: key.ID, DeviceID: key.DeviceID, SharedKeyID: key.SharedKeyID, EncryptedSharedPrivateKey: key.EncryptedSharedPrivateKey})
	}
	return result, nil
}

// Recommendations is the resolver for the recommendations field.
func (r *queryResolver) Recommendations(ctx context.Context, kind model.RecommendationKind) ([]*model.Video, error) {
	videos, err := r.Store.ListVideos(ctx, OwnerID(ctx))
	if err != nil {
		return nil, err
	}
	result := make([]*model.Video, 0, len(videos))
	for _, video := range videos {
		include := false
		switch kind {
		case model.RecommendationKindFavorites:
			include = video.Rating != nil && *video.Rating == 5
		case model.RecommendationKindRecentlyUnplayedFavorites:
			include = video.Rating != nil && *video.Rating == 5 && (video.LastPlayedAt == nil || time.Since(*video.LastPlayedAt) > 30*24*time.Hour)
		case model.RecommendationKindUnwatched:
			include = video.PlayCount == 0
		}
		if include {
			result = append(result, videoModel(video))
		}
	}
	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
