apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: beast-runtime
  namespace: beast
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: beast-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: beast-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: beast/postgres
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: beast/postgres
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: beast/postgres
        property: database
    - secretKey: RABBITMQ_URL
      remoteRef:
        key: beast/rabbitmq
        property: url
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: beast/seaweedfs
        property: accessKey
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        key: beast/seaweedfs
        property: secretKey
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: beast/seaweedfs
        property: accessKey
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: beast/seaweedfs
        property: secretKey
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: beast/oidc
        property: clientId
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: beast/oidc
        property: clientSecret
