apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beast
  namespace: beast
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 2g
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [beast.walnuts.dev]
      secretName: beast-tls
  rules:
    - host: beast.walnuts.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: beast-frontend
                port:
                  name: http
