apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - external-secrets.yaml
  - http-route.yaml
configMapGenerator:
  - name: beast-config
    namespace: beast
    behavior: merge
    literals:
      - AUTH_MODE=introspection
      - OIDC_INTROSPECTION_URL=https://auth.walnuts.dev/oauth/v2/introspect
      - POSTGRES_HOST=postgresql-default-rw.databases.svc.cluster.local
      - POSTGRES_SSLMODE=verify-full
      - S3_ENDPOINT=http://seaweedfs-default-filer.seaweedfs.svc.cluster.local:8333
      - AWS_ENDPOINT_URL=http://seaweedfs-default-filer.seaweedfs.svc.cluster.local:8333
patches:
  - path: image-pull-policy.yaml
  - path: recreate-strategy.yaml
images:
  - name: ghcr.io/walnuts1018/beast/backend
    newTag: 835237b-amd64
  - name: ghcr.io/walnuts1018/beast/encoder
    newTag: 835237b-amd64
  - name: ghcr.io/walnuts1018/beast/frontend
    newTag: 835237b-amd64
