package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/walnuts1018/beast/apiserver/domain"
	"github.com/walnuts1018/beast/apiserver/graph/model"
)

// RegisterSharedKey is the resolver for the registerSharedKey field.
func (r *mutationResolver) RegisterSharedKey(ctx context.Context, input model.RegisterSharedKeyInput) (*model.SharedKeyVersion, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	v, err := r.Service.RegisterSharedKey(ctx, userID, input.PublicKeyPem)
	if err != nil {
		return nil, err
	}

	return toModelSharedKeyVersion(*v), nil
}

// RevokeSharedKeyVersion is the resolver for the revokeSharedKeyVersion field.
func (r *mutationResolver) RevokeSharedKeyVersion(ctx context.Context, input model.RevokeSharedKeyVersionInput) (*model.SharedKeyVersion, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	v, err := r.Service.RevokeSharedKeyVersion(ctx, userID, input.Version)
	if err != nil {
		return nil, err
	}

	return toModelSharedKeyVersion(*v), nil
}

// RegisterDeviceKey is the resolver for the registerDeviceKey field.
func (r *mutationResolver) RegisterDeviceKey(ctx context.Context, input model.RegisterDeviceKeyInput) (*model.DeviceWrappedSharedKey, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	v, err := r.Service.RegisterDeviceKey(
		ctx,
		userID,
		input.DeviceID,
		input.SharedKeyVersion,
		[]byte(input.EncryptedSharedPrivateKey),
	)
	if err != nil {
		return nil, err
	}

	return toModelDeviceWrappedSharedKey(*v), nil
}

// CreateUploadSession is the resolver for the createUploadSession field.
func (r *mutationResolver) CreateUploadSession(ctx context.Context, input model.CreateUploadSessionInput) (*model.UploadSession, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	session, err := r.Service.CreateUploadSession(ctx, userID)
	if err != nil {
		return nil, err
	}

	return toModelUploadSession(*session), nil
}

// CompleteUpload is the resolver for the completeUpload field.
func (r *mutationResolver) CompleteUpload(ctx context.Context, input model.CompleteUploadInput) (*model.Video, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	video, err := r.Service.CompleteUpload(ctx, userID, input.UploadSessionID)
	if err != nil {
		return nil, err
	}

	return toModelVideo(*video), nil
}

// UpdateEncryptedTags is the resolver for the updateEncryptedTags field.
func (r *mutationResolver) UpdateEncryptedTags(ctx context.Context, input model.UpdateEncryptedTagsInput) (*model.Video, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	video, err := r.Service.UpdateEncryptedTags(
		ctx,
		userID,
		input.VideoID,
		[]byte(input.EncryptedTags),
		toDomainEncryptionMetadata(*input.TagEncryption),
	)
	if err != nil {
		return nil, err
	}

	return toModelVideo(*video), nil
}

// RetryEncoding is the resolver for the retryEncoding field.
func (r *mutationResolver) RetryEncoding(ctx context.Context, input model.RetryEncodingInput) (*model.Video, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	video, err := r.Service.RetryEncoding(ctx, userID, input.VideoID)
	if err != nil {
		return nil, err
	}

	return toModelVideo(*video), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.Me, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	me, err := r.Service.Me(ctx, userID)
	if err != nil {
		return nil, err
	}

	return toModelMe(*me), nil
}

// Video is the resolver for the video field.
func (r *queryResolver) Video(ctx context.Context, videoID string) (*model.Video, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	v, err := r.Service.Video(ctx, userID, videoID)
	if err != nil {
		return nil, err
	}
	if v == nil {
		return nil, nil
	}

	return toModelVideo(*v), nil
}

// Videos is the resolver for the videos field.
func (r *queryResolver) Videos(ctx context.Context, status *model.VideoStatus, pagination *model.PaginationInput) (*model.VideoConnection, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	var domainStatus *domain.VideoStatus
	if status != nil {
		st := toDomainVideoStatus(*status)
		domainStatus = &st
	}

	pg := domain.Pagination{First: 20}
	if pagination != nil {
		pg.After = pagination.After
		pg.First = pagination.First
	}

	result, err := r.Service.Videos(ctx, userID, domainStatus, pg)
	if err != nil {
		return nil, err
	}

	return toModelVideoConnection(result), nil
}

// EncodingProgress is the resolver for the encodingProgress field.
func (r *queryResolver) EncodingProgress(ctx context.Context, videoID string) (*model.VideoEncodingProgress, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	progress, err := r.Service.EncodingProgress(ctx, userID, videoID)
	if err != nil {
		return nil, err
	}

	return toModelProgress(*progress), nil
}

// EncodingProgressUpdated is the resolver for the encodingProgressUpdated field.
func (r *subscriptionResolver) EncodingProgressUpdated(ctx context.Context, videoID string) (<-chan *model.VideoEncodingProgress, error) {
	userID, err := userIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	stream, cleanup, err := r.Service.SubscribeEncodingProgress(ctx, userID, videoID)
	if err != nil {
		return nil, err
	}

	out := make(chan *model.VideoEncodingProgress, 8)
	go func() {
		defer close(out)
		defer cleanup()
		for item := range stream {
			converted := toModelProgress(item)
			select {
			case <-ctx.Done():
				return
			case out <- converted:
			}
		}
	}()

	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
