apiVersion: v1
kind: Service
metadata:
  name: beast-frontend
  namespace: beast
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: beast
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
