apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - encoder-deployment.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml
